site_name: Recursos educatius STEAM
site_description: Documentació per al projecte Open STEAM Education Resources
site_author: Enric Balletbo i Serra
repo_url: https://github.com/eballetbo/steam

theme:
  name: material
  language: ca
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

extra:
  alternate:
    # Order the languages alphabetically by name
    - name: Catalan
      link: /ca/
      lang: ca
    - name: English
      link: /en/ 
      lang: en

nav:
  - Sobre el projecte: README.md
  - Blocs numèrics Montessori: 'montessori-number-blocks/README.md'
